name: Publish

on:
  push:
    branches:
      - main # adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Configure Git
      run: |
        git config user.name "Doug Silkstone"
        git config user.email "doug@withseismic.com"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project with prepublishOnly
      run: npm run prepublishOnly

    - name: Check for uncommitted changes
      run: |
        git diff-index --quiet HEAD || (echo "There are uncommitted changes. Please commit or stash them." && exit 1)

    - name: Increment version
      run: npm version patch

    - name: Commit changes
      run: |
        git add package.json
        git commit -m "chore: increment version"
        git push origin main || echo "No changes to push"

    - name: Publish to npm
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
