name: Publish

on:
  push:
    branches:
      - main # adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org' # Required for npm publish

    - name: Configure Git
      run: |
        git config user.name "Your Name"
        git config user.email "you@example.com"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Check for uncommitted changes
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "Uncommitted changes found. Please commit or ignore them before running this action.";
          exit 1;
        fi

    - name: Increment version
      run: |
        npm version patch # You can use 'major', 'minor', or 'patch' as needed
        git push origin main || echo "No changes to push" # Push the commit created by npm version

    - name: Publish to npm
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # make sure to set this in your repository's secrets
