name: Publish

on:
    push:
        branches:
            - main # adjust the branch name as needed

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  registry-url: 'https://registry.npmjs.org'

            - name: Configure Git
              run: |
                  git config user.name "Doug Silkstone"
                  git config user.email "doug@withseismic.com"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build project
              run: npm run build

            - name: Increment version
              run: |
                  npm version patch --no-git-tag-version
                  echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
                  git add package.json
                  git commit -m "Bump version to $NEW_VERSION"
                  git push origin main || echo "No changes to push"

            - name: Create and Push Tag
              run: |
                  git tag v$NEW_VERSION # Prefix the tag with 'v'
                  git push origin v$NEW_VERSION

            - name: Publish to npm
              if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub Release
              uses: actions/create-release@v1
              with:
                  tag_name: v${{ env.NEW_VERSION }} # Use the new version number as the tag name
                  release_name: Release v${{ env.NEW_VERSION }}
                  body: Auto-generated release from GitHub Actions.
                  draft: true
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
