name: Publish

on:
  push:
    branches:
      - main # adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org' # Required for npm publish

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Increment version
      run: npm version patch # You can use 'major', 'minor', or 'patch' as needed

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # make sure to set this in your repository's secrets

    # Optional: Add the dist directory and updated package.json to the commit
    - name: Commit changes
      run: |
        git add dist/* package.json CHANGELOG.md README.md
        git commit -m "chore: Add built files and increment version" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
