name: Publish

on:
  push:
    branches:
      - main # adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Setup Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # make sure to set this in your repository's secrets
      run: npx semantic-release

    # Optional: Add the dist directory to the commit
    - name: Commit dist directory
      run: |
        git add dist/*
        git commit -m "chore: Add built files" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
